pre-commit:
  parallel: false
  jobs:
    - name: 'Lint and Fix Coding Style'
      stage_fixed: true
      exclude:
        - 'node_modules/**'
      glob:
        - 'src/*.js'
        - 'eslint.config.js'
        - '*.json'
      run: npm run lint lint:fix && npx prettier --write {staged_files}

    - name: 'test'
      run: npm test
      stage_fixed: true

# Build commit messages
prepare-commit-msg:
  jobs:
    - name: 'Prepare Conventional Commit Message'
      interactive: true
      env:
        LEFTHOOK: '0'
      skip:
        - merge
        - rebase
      run: |
        php -r 'echo "⏳ Openning Conventional Commit Prompt...\n";'
        npx cz --hook

# Validate commit messages
commit-msg:
  jobs:
    - name: 'Lint Commit Message'
      skip:
        - merge
        - rebase
      run: npx commitlint --edit {1}

output:
  - summary
  - success
  - failure
  - execution_out
