name: Coverage Report

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Testing on Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Version Check
        run: node -v && npm -v
      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
