name: Prepare Environment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Testing on Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Version Check
        run: node -v && npm -v
      - name: Install dependencies
        run: npm ci
